### ISSUE TITLE
Nearline is HSM 

### ISSUE THREAD

**Issue by pletzer** [nesi/hpc_training#17]
Instead of backed up in slide 006.  Also use "huge" instead of large. Also need to define HSM. 

home 50TB
projects 300TB
nobackup 2500TB
nearline 600 TB + 50 PB

/devel 50TB
/
/archive 100 TB
/

**Comment by pletzer** [comment]
Added the partition sizes

**Comment by tinyendian** [comment]
Added to the lesson.
