### ISSUE TITLE
issue with: Logging in [to kupe] from outside of NIWA computer network (advanced)

### ISSUE THREAD

**Issue by jonnyhtw** [nesi/hpc_training#38]
Hi there

@vv1610 has noticed (and I've confirmed) that the guidance in the 'Logging in from outside of NIWA computer network (advanced)' on [this](https://nesi.github.io/hpc_training/lessons/kupe-access/) page is not working...

`Host kupe`
   `User your_username`
   `Hostname login.kupe.niwa.co.nz`
   `ProxyCommand ssh -W %h:%p lander.nesi.org.nz`
   `ForwardX11 yes`
   `ForwardX11Trusted yes`

We have found that this longer solution does work however...

`Host kupe`
 `   User your_username`
  `  HostName login.kupe.niwa.co.nz`
   ` ProxyCommand ssh -W %h:%p lander`
   ` ForwardX11 yes`
   ` ForwardX11Trusted yes`
   ` ServerAliveInterval 300`
   ` ServerAliveCountMax 2`

`Host lander`
    `User your_username`
  `  HostName lander.nesi.org.nz`
    `ForwardX11 yes`
    `ForwardX11Trusted yes`
    `ServerAliveInterval 300`
    `ServerAliveCountMax 2`

`Host *`
 `   ControlMaster auto`
  `  ControlPath ~/.ssh/ssh_mux_%h_%p_%r`
   ` ControlPersist 1`

Not sure if this is an issue only for us? If it affects everyone then I guess this page should be updated.

Thanks

**Comment by chrisdjscott** [comment]
What is the error you are getting? The documented config is working for me and can't see any obvious difference with the config that works for you (other than multiplexing and keep alive, which shouldn't be relevant).

**Comment by jonnyhtw** [comment]
Hey there

Basically it continually asks for `password` which is seemingly never recognised, rather than `first factor` then `second factor (optional)` then `password` as for the working solution.

Cheers

Jonny

**Comment by chrisdjscott** [comment]
Has this only become a problem recently - i.e. the documented config was working for you before and then stopped working? Or did you never try before with the documented config?

**Comment by VidyaVR** [comment]
I (we) have never tried the option from documented page before.
Basically, the working version for us is:

**Host kupe
User your_username
HostName login.kupe.niwa.co.nz
ProxyCommand ssh -W %h:%p lander
ForwardX11 yes
ForwardX11Trusted yes
ServerAliveInterval 300
ServerAliveCountMax 2

Host lander
User your_username
HostName lander.nesi.org.nz
ForwardX11 yes
ForwardX11Trusted yes
ServerAliveInterval 300
ServerAliveCountMax 2

Host *
ControlMaster auto
ControlPath ~/.ssh/ssh_mux_%h_%p_%r
ControlPersist 1**

Cheers
Vidya

**Comment by JHigino** [comment]
Thank you @jonnyhtw. I have tested this myself. Will spawn a fix for this on the documentation.

**Comment by jonnyhtw** [comment]
OK cool, thanks!

Jonny

**Comment by chrisdjscott** [comment]
@JHigino when I tried connecting from home with the original configuration it didn't work for me either, but it works perfectly well when I am in the UoA network - any idea why this is? Are you treating connections from within UoA differently to those outside? Any idea why one of the configs is working and the other not?

**Comment by JHigino** [comment]
@chrisdjscott we have an ongoing bug that is causing some confusions. @Aethylred and me are trying to understand what could be causing this. Can you test if using the config above you also get through correctly? And, for the case you specify, coming from UoA, do you get asked the "First factor" on the first jump? or "Password"?

**Comment by JHigino** [comment]
#39 Submitted

**Comment by chrisdjscott** [comment]
@JHigino yes the new config you've added works for me too. Coming from UoA it asks first factor, second factor and then puts me straight through to kupe (might have expected a third password to get onto kupe?).

**Comment by JHigino** [comment]
@chrisdjscott , are you using any SSH keys from lander to kupe? Possibly that is why it does not ask you.

**Comment by chrisdjscott** [comment]
@JHigino no I haven't setup SSH keys. If I ssh to lander first and then a second ssh to kupe it asks for a password, but if I do it in one ssh, using proxycommand, it doesn't ask for the final password

**Comment by JHigino** [comment]
@chrisdjscott Ok Thanks. Another case to double check with @Aethylred.
